### ISSUE TITLE
Problema com os dados populacionais

### ISSUE THREAD

**Issue by igorvc30** [LucasReSilva/COMP0257-SISTEMAS-DE-APOIO-A-DECISAO-2018.1-T01#1]
Os dados populacionais estão incompletos, está faltando os dados de muitos municípios dos estados em questão. No arquivo existe cerca de 1/4 dos municípios de cada estado.

**Comment by LucasReSilva** [comment]
Fixed, tinha configurado o etl de forma equivocada, a ferramenta estava dividindo as linhas entre as saidas.
